### ISSUE TITLE
Falha ao renderizar o widget de libras

### ISSUE THREAD

**Issue by alexandre-codyus** [vandsonfalcao/vlibras-nextjs#2]
Olá, tudo bem ?

Recebo os erros abaixo mesmo quando eu vou executar sua página de exemplo (no meu projeto dá os mesmos erros), obtidos pelo console, ao acessar a url https://vlibras-nextjs-example.vercel.app pelo Google Chrome:

UnityLoader.js:4 failed to asynchronously prepare wasm: LinkError: WebAssembly.instantiate(): table import 1 has a larger maximum size cca7 than the module's declared maximum 52381

UnityLoader.js:4 LinkError: WebAssembly.instantiate(): table import 1 has a larger maximum size cca7 than the module's declared maximum 52381

Uncaught (in promise) abort({}) at Error
    at jsStackTrace (blob:https://vlibras-nextjs-example.vercel.app/b988c932-01fa-4445-9ab2-630ca93ab605:2:15158)
    at Object.stackTrace (blob:https://vlibras-nextjs-example.vercel.app/b988c932-01fa-4445-9ab2-630ca93ab605:2:15329)
    at Object.onAbort (https://cdn.jsdelivr.net/gh/spbgovbr-vlibras/vlibras-portal@dev/app/target/UnityLoader.js:4:8856)
    at abort (blob:https://vlibras-nextjs-example.vercel.app/b988c932-01fa-4445-9ab2-630ca93ab605:2:482237)
    at blob:https://vlibras-nextjs-example.vercel.app/b988c932-01fa-4445-9ab2-630ca93ab605:2:24944

**Comment by vandsonfalcao** [comment]
Olá @alexandre-codyus 

Sinto muito pela demora em responde-lo, enfrentei um grande problema em tentar utilizar essa lib do governo em um projeto que participei, como consegui fazer funcionar decidi compartilhar com a comunidade, o github nao me notificou sua issue sinto muito por isso.

Qual a versao do nextjs do seu app?
Qual a versao do node do seu app?

eu reproduzi e um novo repositorio em uma versao mais recente do next(https://github.com/vandsonfalcao/vlibras-nextjs-15-example) fiz um pequeno teste no navegador chrome

Poderia mandar um repositorio para reproduzir o erro? Talvez eu consiga ajuda-lo

https://github.com/user-attachments/assets/f65b841e-ac80-4cef-bb50-042a4d9eae83

**Comment by alexandre-codyus** [comment]
Infelizmente não somos mais fornecedores do cliente que teve o problema.  Farei um novo uso na próxima semana e aviso se tiver algum problema.  Obrigado pela resposta.
